import { v4 as uuid } from 'uuid'

let inventory = [
    {
        categories: ['men'],
        name: 'MEN CLOUDFOAM ADAPT 3.0 SLIP ON SNEAKER',
        price: '64.99',
        image: '/images/shoes1.png',
        description: 'Angular is a platform and framework for building single-page client applications using HTML and TypeScript. Angular is written in TypeScript. ... An app always has at least a root module that enables bootstrapping, and typically has many more feature modules.',
        brand: 'Jordan Walke',
        currentInventory: 4,
    },
    {
        categories: ['frontend'],
        name: 'React Courses',
        price: '800',
        image: '/images/fe-courses2.png',
        description: 'React is a library for building composable user interfaces. It encourages the creation of reusable UI components, which present data that changes over time. ... React can also render on the server using Node, and it can power native apps using React Native.',
        brand: 'Jordan Walke',
        currentInventory: 8,
    },
    {
        categories: ['frontend'],
        name: 'Vue Courses',
        price: '600',
        image: '/images/fe-courses3.png',
        description: 'Vue.js is a library for building interactive web interfaces. The goal of Vue.js is to provide the benefits of reactive data binding and composable view components with an API that is as simple as possible.',
        brand: 'Evan You',
        currentInventory: 3,
    },
    {
        categories: ['frontend'],
        name: 'Next Courses',
        price: '800',
        image: '/images/fe-courses4.png',
        description: 'Next. js provides a backend that can server side render a response to request, allowing you to create a dynamic website, which means you will deploy it on a platform that can run Node. js.',
        brand: 'Guillermo Rauch',
        currentInventory: 5,
    },
    {
        categories: ['frontend'],
        name: 'Ember js Courses',
        price: '300',
        image: '/images/fe-courses5.png',
        description: 'Ember. js is a productive, battle-tested JavaScript framework for building modern web applications. It includes everything you need to build rich UIs that work on any device.',
        brand: 'Yehuda Katz',
        currentInventory: 2,
    },
    {
        categories: ['frontend', 'backend'],
        name: 'Vanilla Js Courses',
        price: '1200',
        image: '/images/fe-courses6.png',
        description: 'VanillaJS is a name to refer to using plain JavaScript without any additional libraries like jQuery. People use it as a joke to remind other developers that many things can be done nowadays without the need for additional JavaScript libraries." Or, in our case, without new, fancy frameworks.',
        brand: 'Brendan Eich',
        currentInventory: 7,
    },
    {
        categories: ['frontend'],
        name: 'Aurelia Courses',
        price: '500',
        image: '/images/fe-courses7.png',
        description: 'Aurelia is a collection of Modern JavaScript modules, which when used together, function as a powerful platform for building browser, desktop and mobile applications, all open source and built on open web standards.',
        brand: 'Rob Eisenberg',
        currentInventory: 4,
    },
    {
        categories: ['frontend'],
        name: 'WordPress Courses',
        price: '1600',
        image: '/images/fe-courses8.png',
        description: 'Overview. "WordPress is a factory that makes webpages" is a core analogy designed to clarify the functions of WordPress: it stores content and enables a user to create and publish webpages, requiring nothing beyond a domain and a hosting service. WordPress has a web template system using a template processor.',
        brand: 'Google',
        currentInventory: 13,
    },
    {
        categories: ['backend'],
        name: 'Nodejs/Express Courses',
        price: '1400',
        image: '/images/be-courses1.png',
        description: 'Node. js (Node) is an open source development platform for executing JavaScript code server-side. Node is useful for developing applications that require a persistent connection from the browser to the server and is often used for real-time applications such as chat, news feeds and web push notifications.',
        brand: 'Ryan Dahl',
        currentInventory: 9,
    },
    {
        categories: ['backend'],
        name: 'Golang Courses',
        price: '800',
        image: '/images/be-courses2.png',
        description: 'Go (also called Golang or Go language) is an open source programming language used for general purpose. Go was developed by Google engineers to create dependable and efficient software. Most similarly modeled after C, Go is statically typed and explicit.',
        brand: 'Robert Griesemer Rob Pike Ken Thompson',
        currentInventory: 3,
    },
    {
        categories: ['backend'],
        name: 'ASP.NET Courses',
        price: '1000',
        image: '/images/be-courses3.png',
        description: 'ASP.NET is an open-source, server-side web-application framework designed for web development to produce dynamic web pages. It was developed by Microsoft to allow programmers to build dynamic web sites, applications and services. ... NET Framework and is the successor to Microsoft is Active Server Pages (ASP) technology.',
        brand: 'Microsoft',
        currentInventory: 6,
    },
    {
        categories: ['backend'],
        name: 'Nest Courses',
        price: '600',
        image: '/images/be-courses4.png',
        description: 'Nest (NestJS) is a framework for building efficient, scalable Node.js server-side applications. It uses progressive JavaScript, is built with and fully supports TypeScript (yet still enables developers to code in pure JavaScript) and combines elements of OOP (Object Oriented Programming), FP (Functional Programming), and FRP (Functional Reactive Programming).',
        brand: 'Kamil Myśliwiec',
        currentInventory: 7,
    },
    {
        categories: ['backend'],
        name: 'Django Courses',
        price: '1000',
        image: '/images/be-courses5.png',
        description: 'Django is a high-level Python web framework that enables rapid development of secure and maintainable websites. Built by experienced developers, Django takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel.',
        brand: 'Adrian Holovaty',
        currentInventory: 8,
    },
    {
        categories: ['backend', 'frontend'],
        name: 'Laravel Courses',
        price: '1800',
        image: '/images/be-courses6.png',
        description: 'Laravel is a web application framework with expressive, elegant syntax. ... Laravel attempts to take the pain out of development by easing common tasks used in the majority of web projects, such as authentication, routing, sessions, and caching.',
        brand: 'Taylor Otwell',
        currentInventory: 9,
    },
    {
        categories: ['backend'],
        name: 'Phoenix Courses',
        price: '800',
        image: '/images/be-courses7.png',
        description: 'Phoenix is a web development framework written in Elixir which implements the server-side Model View Controller (MVC) pattern. Many of its components and concepts will seem familiar to those of us with experience in other web frameworks like Ruby on Rails or Python is Django.',
        brand: 'Chris McCord',
        currentInventory: 4,
    },
    {
        categories: ['backend'],
        name: 'Spring Boot Courses',
        price: '1200',
        image: '/images/be-courses8.png',
        description: 'The Spring Framework (Spring) is an open-source application framework that provides infrastructure support for developing Java applications. One of the most popular Java Enterprise Edition (Java EE) frameworks, Spring helps developers create high performing applications using plain old Java objects (POJOs).',
        brand: 'Rod Johnson',
        currentInventory: 8,
    },
    {
        categories: ['backend'],
        name: 'Flask Courses',
        price: '700',
        image: '/images/be-courses9.png',
        description: 'Flask is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries. It has no database abstraction layer, form validation, or any other components where pre-existing third-party libraries provide common functions.',
        brand: 'Armin Ronacher',
        currentInventory: 3,
    },
    {
        categories: ['backend'],
        name: 'Ruby on Rails Courses',
        price: '1400',
        image: '/images/be-courses10.png',
        description: 'Ruby on Rails, sometimes known as "RoR" or just "Rails," is an open source framework for Web development in Ruby, an object-oriented programming (OOP) language similar to Perl and Python. ... According to David Geary, a Java expert, the Ruby-based framework is five to 10 times faster than comparable Java-based frameworks.',
        brand: 'David Heinemeier Hansson',
        currentInventory: 6,
    },
]

inventory.map(i => {
    i.id = uuid()
    return i
})

export default inventory